import Navbar from "@/components/shared/Navbar/Navbar";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
const crimsonPro = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen scroll-smooth bg-[#fffff8] antialiased",
          crimsonPro.className,
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
